export type Locale = "en" | "fr" | "ru";
export type DirectionKey =
  | "business"
  | "property"
  | "relocation"
  | "mobility"
  | "brand";

export type LocalizedPillar = {
  title: string;
  tagline: string;
  summary: string;
  groups: { title: string; items: string[] }[];
};

export const concepts = [
  {
    slug: "continuous-passage",
    name: "Continuous Passage",
    number: "01",
    description: "One continuous route through five fields.",
    className: "passage",
    image: "/assets/01_continuous_passage.png",
    palette: {
      bg: "#f3efe6",
      ink: "#082d4c",
      accent: "#167ba5",
      signal: "#b48a57",
      surface: "#fcfaf5",
    },
  },
  {
    slug: "discreet-layers",
    name: "Discreet Layers",
    number: "02",
    description: "Confidentiality through controlled disclosure.",
    className: "layers",
    image: "/assets/02_discreet_layers.png",
    palette: {
      bg: "#050b11",
      ink: "#f1ece2",
      accent: "#b99a6b",
      signal: "#87afc2",
      surface: "#0d1821",
    },
  },
  {
    slug: "five-orbits",
    name: "Five Orbits",
    number: "03",
    description: "Five fields coordinated around one stable center.",
    className: "orbits",
    image: "/assets/03_five_orbits.png",
    palette: {
      bg: "#f3eee4",
      ink: "#173e47",
      accent: "#1b7894",
      signal: "#c77547",
      surface: "#fffdf8",
    },
  },
  {
    slug: "riviera-frames",
    name: "Riviera Frames",
    number: "04",
    description: "A cinematic Riviera story in five chapters.",
    className: "frames",
    image: "/assets/04_riviera_frames.png",
    palette: {
      bg: "#ede7da",
      ink: "#162431",
      accent: "#a26f40",
      signal: "#5c8292",
      surface: "#f8f5ed",
    },
  },
  {
    slug: "convergent-grid",
    name: "Convergent Grid",
    number: "05",
    description: "Many moving parts, one aligned operating system.",
    className: "grid",
    image: "/assets/05_convergent_grid.png",
    palette: {
      bg: "#f4f3ee",
      ink: "#14243b",
      accent: "#075fcc",
      signal: "#58a8c8",
      surface: "#ffffff",
    },
  },
] as const;

export type Concept = (typeof concepts)[number];

const data = {
  en: {
    nav: {
      approach: "Approach",
      expertise: "Expertise",
      how: "How we work",
      confidentiality: "Confidentiality",
      contact: "Contact",
      faq: "FAQ",
      request: "Make a private request",
      menuOpen: "Open menu",
      menuClose: "Close menu",
      skip: "Skip to content",
    },
    hero: {
      eyebrow: "Private Office Consulting · French Riviera",
      title: "One call. Everything else is our concern.",
      body: "Consulting, concierge service and coordination for private and professional matters on the French Riviera and beyond.",
      primary: "Make a private request",
      secondary: "Explore our expertise",
      scroll: "Discover POC",
    },
    positioning: {
      label: "The purpose of our work",
      title: "Complex matters, brought into focus.",
      paragraphs: [
        "One accountable contact brings the right people, decisions and next steps into one coordinated process.",
        "We step in where speed, sound judgment and complete confidentiality matter. No impersonal service packages.",
        "Every engagement begins with one question — what truly matters here? Only then do we build the shortest, most reliable solution.",
      ],
      assurances: [
        "One accountable contact",
        "A clear first response",
        "End-to-end coordination",
        "Strict confidentiality",
      ],
    },
    expertise: {
      label: "Five fields",
      title: "Broad expertise. One standard of execution.",
      body: "Choose the closest direction or tell us the outcome you need. Complex requests often cross several fields; POC keeps them under one coordinated plan.",
      services: "Services",
      close: "Close",
      discuss: "Make a request",
      select: "Select direction",
    },
    custom: {
      label: "Custom request",
      title: "Not everything important fits a category.",
      body: "Does your request fit none of these directions? That is precisely where we can help. Tell us the outcome you need; we will identify what matters and propose the right next step.",
      cta: "Describe your request",
    },
    method: {
      label: "Our method",
      title: "A calm process from question to completion.",
      steps: [
        "Tell us what needs to be resolved.",
        "We clarify what truly matters.",
        "You receive a clear first response and proposed route.",
        "One contact coordinates execution through to completion.",
      ],
    },
    confidentiality: {
      label: "Confidentiality",
      title: "Confidentiality is built into the process.",
      body: "Your matter is handled through the smallest practical circle of people. We ask only for what is necessary, coordinate qualified specialists where required and keep communication clear.",
      points: [
        "Need-to-know coordination",
        "No public case studies without explicit consent",
        "Qualified specialists for regulated matters",
      ],
    },
    form: {
      label: "Individual request",
      title: "Tell us what needs to be resolved.",
      body: "We will return with a clear first response — confidentially and to the point.",
      name: "Name",
      email: "Email",
      phone: "Phone (optional)",
      direction: "Direction",
      task: "What needs to be resolved?",
      select: "Choose a direction",
      custom: "Custom request",
      submit: "Send request",
      sending: "Sending securely…",
      successTitle: "Your request is with POC.",
      successBody: "Thank you. Your message has been accepted and this form has been cleared.",
      another: "Send another request",
      privacy: "Your request is treated with strict confidentiality. Please do not include highly sensitive personal data at this stage.",
      required: "This field is required.",
      invalidEmail: "Enter a valid email address.",
      shortTask: "Please add a little more detail.",
      sendError: "We could not accept the request just now. Please try again or use a direct channel.",
      channelTitle: "Prefer a direct channel?",
      unavailable: "Official details will be added before launch.",
    },
    footer: {
      line: "Discretion · Clarity · Follow-through",
      region: "French Riviera and beyond",
      linksLabel: "Footer navigation",
      faq: "FAQ",
      privacy: "Privacy",
      legal: "Legal notice",
      rights: "Private Office Consulting. All rights reserved.",
      concepts: "View all five directions",
    },
    card: {
      view: "View site",
      preferred: "Recommended",
      title: "Five working POC experiences.",
      body: "Choose a direction. Every version contains the same complete service offer, trilingual content and confidential request path, expressed through a different motion system.",
    },
    faq: {
      label: "FAQ",
      title: "Before your first request.",
      toggle: "Have a question before your first request?",
      body: "The essentials to know before we begin.",
      pageTitle: "Your questions, answered.",
      pageBody: "A few clear answers about how POC works, what we coordinate and what happens when you get in touch.",
      groups: ["Getting started", "What we coordinate", "Process & confidentiality"],
      groupBodies: ["Where every request begins.", "The kind of situations we can bring into focus.", "What to expect once the conversation starts."],
      ctaTitle: "Still have a question?",
      ctaBody: "The most useful answer often starts with the conversation itself.",
      back: "Back to POC",
      ctaPrompt: "Didn't find what you were looking for?",
      cta: "Make an individual request",
      more: "Learn more",
      less: "Close FAQ",
      items: [
        { question: "What kind of requests do you handle?", answer: "We coordinate private and professional matters across business, property, relocation, mobility and digital presence." },
        { question: "Can I send an individual request?", answer: "Yes. If your situation does not fit one direction, choose Custom request and describe the outcome you need." },
        { question: "What happens after I send a request?", answer: "We review the brief, ask only the necessary questions and return with a clear first response and proposed next step." },
        { question: "What information is needed at first?", answer: "A short description of the situation, the outcome you want and any relevant timing is enough. Please do not send sensitive documents at this stage." },
        { question: "Can one request cover several directions?", answer: "Yes. Complex matters can be coordinated under one plan and through one accountable contact." },
        { question: "How is my information handled?", answer: "Your request is kept within the smallest practical circle needed to move it forward. We do not publish case studies without explicit consent." },
        { question: "Does sending a request commit me to anything?", answer: "No. A request starts a conversation; any scope, fees or next steps are agreed separately." },
      ],
    },
  },
  fr: {
    nav: {
      approach: "Notre approche",
      expertise: "Expertises",
      how: "Notre méthode",
      confidentiality: "Confidentialité",
      contact: "Contact",
      faq: "FAQ",
      request: "Faire une demande privée",
      menuOpen: "Ouvrir le menu",
      menuClose: "Fermer le menu",
      skip: "Aller au contenu",
    },
    hero: {
      eyebrow: "Private Office Consulting · Côte d’Azur",
      title: "Un appel. Nous nous occupons de tout le reste.",
      body: "Conseil, conciergerie et coordination pour vos enjeux privés et professionnels sur la Côte d’Azur et au-delà.",
      primary: "Faire une demande privée",
      secondary: "Découvrir nos expertises",
      scroll: "Découvrir POC",
    },
    positioning: {
      label: "Le sens de notre engagement",
      title: "Les situations complexes, clarifiées.",
      paragraphs: [
        "Un interlocuteur responsable réunit les bonnes expertises, les décisions et les prochaines étapes dans une coordination unique.",
        "Nous intervenons là où la rapidité, le discernement et une confidentialité absolue sont essentiels. Aucune formule impersonnelle.",
        "Chaque mission commence par une seule question : qu’est-ce qui compte vraiment ici ? C’est ensuite que nous construisons la solution la plus directe et la plus fiable.",
      ],
      assurances: [
        "Un interlocuteur responsable",
        "Une première réponse claire",
        "Une coordination de bout en bout",
        "Une confidentialité absolue",
      ],
    },
    expertise: {
      label: "Cinq expertises",
      title: "Une expertise étendue. Un même niveau d’exécution.",
      body: "Choisissez l’expertise la plus proche de votre besoin ou indiquez-nous le résultat recherché. POC réunit les demandes complexes dans un plan coordonné.",
      services: "Services",
      close: "Fermer",
      discuss: "Faire une demande",
      select: "Choisir cette expertise",
    },
    custom: {
      label: "Demande sur mesure",
      title: "L’essentiel ne rentre pas toujours dans une catégorie.",
      body: "Votre demande ne correspond à aucune de ces expertises ? C’est précisément là que nous pouvons être utiles. Indiquez-nous le résultat recherché ; nous identifierons l’essentiel et proposerons la prochaine étape appropriée.",
      cta: "Décrire votre demande",
    },
    method: {
      label: "Notre méthode",
      title: "Un processus serein, de la question à sa résolution.",
      steps: [
        "Dites-nous ce qu’il faut résoudre.",
        "Nous clarifions ce qui compte vraiment.",
        "Vous recevez une première réponse claire et un plan d’action.",
        "Un interlocuteur coordonne l’exécution jusqu’à son terme.",
      ],
    },
    confidentiality: {
      label: "Confidentialité",
      title: "La confidentialité est intégrée à chaque étape.",
      body: "Votre demande est traitée par le cercle de personnes le plus restreint possible. Nous ne demandons que l’essentiel et coordonnons des spécialistes qualifiés lorsque nécessaire.",
      points: [
        "Coordination selon le besoin d’en connaître",
        "Aucune étude de cas publique sans consentement explicite",
        "Spécialistes qualifiés pour les matières réglementées",
      ],
    },
    form: {
      label: "Demande personnalisée",
      title: "Dites-nous ce qu’il faut résoudre.",
      body: "Nous reviendrons avec une première réponse claire — en toute confidentialité et sans détour.",
      name: "Nom",
      email: "E-mail",
      phone: "Téléphone (facultatif)",
      direction: "Expertise",
      task: "Que faut-il résoudre ?",
      select: "Choisir une expertise",
      custom: "Demande sur mesure",
      submit: "Envoyer la demande",
      sending: "Envoi sécurisé…",
      successTitle: "Votre demande a bien été transmise à POC.",
      successBody: "Merci. Votre message a été accepté et ce formulaire a été effacé.",
      another: "Envoyer une autre demande",
      privacy: "Votre demande est traitée en toute confidentialité. Merci de ne pas transmettre de données personnelles très sensibles à ce stade.",
      required: "Ce champ est obligatoire.",
      invalidEmail: "Saisissez une adresse e-mail valide.",
      shortTask: "Merci d’ajouter quelques précisions.",
      sendError: "La demande n’a pas pu être transmise. Réessayez ou utilisez un contact direct.",
      channelTitle: "Vous préférez un contact direct ?",
      unavailable: "Les coordonnées officielles seront ajoutées avant le lancement.",
    },
    footer: {
      line: "Discrétion · Clarté · Suivi",
      region: "Côte d’Azur et au-delà",
      linksLabel: "Navigation du pied de page",
      faq: "FAQ",
      privacy: "Confidentialité",
      legal: "Mentions légales",
      rights: "Private Office Consulting. Tous droits réservés.",
      concepts: "Voir les cinq directions",
    },
    card: {
      view: "Voir le site",
      preferred: "Recommandé",
      title: "Cinq expériences POC fonctionnelles.",
      body: "Choisissez une direction. Chaque version propose la même offre complète, le contenu trilingue et une demande confidentielle, avec un système de mouvement distinct.",
    },
    faq: {
      label: "FAQ",
      title: "Avant votre première demande.",
      toggle: "Une question avant votre première demande ?",
      body: "L’essentiel à savoir avant de commencer.",
      pageTitle: "Vos questions, avec des réponses claires.",
      pageBody: "Quelques repères pour comprendre notre manière de travailler, les situations que nous coordonnons et la suite d’un premier échange.",
      groups: ["Commencer", "Ce que nous coordonnons", "Processus & confidentialité"],
      groupBodies: ["Là où chaque demande commence.", "Les situations que nous pouvons clarifier et coordonner.", "Ce qui se passe après le premier échange."],
      ctaTitle: "Une autre question ?",
      ctaBody: "La réponse la plus utile commence souvent par une conversation.",
      back: "Retour à POC",
      ctaPrompt: "Vous n’avez pas trouvé votre réponse ?",
      cta: "Faire une demande sur mesure",
      more: "En savoir plus",
      less: "Fermer la FAQ",
      items: [
        { question: "Quels types de demandes accompagnez-vous ?", answer: "Nous coordonnons des enjeux privés et professionnels liés à l’entreprise, l’immobilier, la relocalisation, la mobilité et la présence digitale." },
        { question: "Puis-je envoyer une demande sur mesure ?", answer: "Oui. Si votre situation ne correspond pas à une expertise, choisissez Demande sur mesure et décrivez le résultat recherché." },
        { question: "Que se passe-t-il après l’envoi ?", answer: "Nous lisons votre demande, posons uniquement les questions nécessaires et revenons avec une première réponse claire et une prochaine étape." },
        { question: "Quelles informations faut-il fournir au départ ?", answer: "Une courte description de la situation, du résultat souhaité et du calendrier suffit. Merci de ne pas envoyer de documents sensibles à ce stade." },
        { question: "Une demande peut-elle couvrir plusieurs expertises ?", answer: "Oui. Les situations complexes peuvent être coordonnées dans un même plan, avec un interlocuteur responsable." },
        { question: "Comment mes informations sont-elles traitées ?", answer: "Votre demande reste dans le cercle de personnes strictement nécessaire. Aucun cas n’est publié sans consentement explicite." },
        { question: "L’envoi d’une demande m’engage-t-il ?", answer: "Non. La demande ouvre une conversation ; le périmètre, les honoraires et les prochaines étapes sont convenus séparément." },
      ],
    },
  },
  ru: {
    nav: {
      approach: "Подход",
      expertise: "Направления",
      how: "Как мы работаем",
      confidentiality: "Конфиденциальность",
      contact: "Контакты",
      faq: "FAQ",
      request: "Оставить частный запрос",
      menuOpen: "Открыть меню",
      menuClose: "Закрыть меню",
      skip: "Перейти к содержанию",
    },
    hero: {
      eyebrow: "Private Office Consulting · Лазурный берег",
      title: "Один звонок. Всё остальное — наша забота.",
      body: "Консалтинг, консьерж-сервис и координация личных и профессиональных задач на Лазурном берегу и за его пределами.",
      primary: "Оставить частный запрос",
      secondary: "Изучить направления",
      scroll: "Узнать о POC",
    },
    positioning: {
      label: "Смысл нашей работы",
      title: "Сложные задачи — в ясном фокусе.",
      paragraphs: [
        "Один ответственный контакт объединяет нужных специалистов, решения и следующие шаги в едином процессе.",
        "Мы подключаемся там, где нужны скорость, здравый смысл и полная конфиденциальность. Никаких безликих пакетов услуг.",
        "Каждая работа начинается с одного вопроса — что здесь по-настоящему важно, — и только потом мы строим самое короткое и надёжное решение.",
      ],
      assurances: [
        "Одна ответственная точка контакта",
        "Первый чёткий ответ",
        "Координация от начала до конца",
        "Строгая конфиденциальность",
      ],
    },
    expertise: {
      label: "Пять направлений",
      title: "Широкая экспертиза. Единый уровень исполнения.",
      body: "Выберите ближайшее направление или просто опишите желаемый результат. Сложные запросы часто охватывают несколько сфер — POC объединяет их в единый план действий.",
      services: "Услуги",
      close: "Закрыть",
      discuss: "Сделать запрос",
      select: "Выбрать направление",
    },
    custom: {
      label: "Индивидуальный запрос",
      title: "Не всё важное вписывается в категории.",
      body: "Ваш запрос не вписывается ни в одно направление? Именно здесь мы полезны. Опишите желаемый результат — мы выделим главное и предложим следующий разумный шаг.",
      cta: "Описать запрос",
    },
    method: {
      label: "Как мы работаем",
      title: "Спокойный процесс — от вопроса до результата.",
      steps: [
        "Расскажите, что нужно решить.",
        "Мы уточняем, что действительно важно.",
        "Вы получаете первый чёткий ответ и предложенный план.",
        "Одна точка контакта ведёт исполнение до результата.",
      ],
    },
    confidentiality: {
      label: "Конфиденциальность",
      title: "Конфиденциальность встроена в процесс.",
      body: "Вашей задачей занимается минимально необходимый круг людей. Мы запрашиваем только нужную информацию, подключаем профильных специалистов и сохраняем ясность коммуникации.",
      points: [
        "Координация по принципу необходимого знания",
        "Никаких публичных кейсов без прямого согласия",
        "Профильные специалисты для регулируемых вопросов",
      ],
    },
    form: {
      label: "Индивидуальный запрос",
      title: "Расскажите, что нужно решить.",
      body: "Мы вернёмся с первым чётким ответом — конфиденциально и по существу.",
      name: "Имя",
      email: "Email",
      phone: "Телефон (необязательно)",
      direction: "Направление",
      task: "Что нужно решить?",
      select: "Выберите направление",
      custom: "Индивидуальный запрос",
      submit: "Отправить заявку",
      sending: "Защищённая отправка…",
      successTitle: "Ваш запрос передан POC.",
      successBody: "Спасибо. Сообщение принято, а форма очищена.",
      another: "Отправить новый запрос",
      privacy: "Ваш запрос обрабатывается строго конфиденциально. Пожалуйста, не указывайте особо чувствительные персональные данные на этом этапе.",
      required: "Заполните это поле.",
      invalidEmail: "Укажите корректный email.",
      shortTask: "Добавьте немного больше информации.",
      sendError: "Сейчас не удалось принять запрос. Попробуйте ещё раз или свяжитесь напрямую.",
      channelTitle: "Удобнее связаться напрямую?",
      unavailable: "Официальные контакты будут добавлены перед запуском.",
    },
    footer: {
      line: "Конфиденциальность · Ясность · Результат",
      region: "Лазурный берег и за его пределами",
      linksLabel: "Навигация в подвале",
      faq: "FAQ",
      privacy: "Конфиденциальность",
      legal: "Правовая информация",
      rights: "Private Office Consulting. Все права защищены.",
      concepts: "Посмотреть пять направлений",
    },
    card: {
      view: "Открыть сайт",
      preferred: "Рекомендуем",
      title: "Пять рабочих версий POC.",
      body: "Выберите направление. Во всех версиях представлены полный набор услуг, три языка и конфиденциальная форма — в разных motion-системах.",
    },
    faq: {
      label: "FAQ",
      title: "Перед первым запросом.",
      toggle: "Есть вопрос перед первым запросом?",
      body: "Главное, что стоит знать до начала разговора.",
      pageTitle: "Ваши вопросы — с ясными ответами.",
      pageBody: "Несколько ориентиров о том, как работает POC, какие задачи мы координируем и что происходит после первого обращения.",
      groups: ["С чего начать", "Что мы координируем", "Процесс и конфиденциальность"],
      groupBodies: ["С этого начинается каждый запрос.", "Задачи, которые мы можем прояснить и скоординировать.", "Что происходит после первого разговора."],
      ctaTitle: "Остался вопрос?",
      ctaBody: "Самый полезный ответ часто начинается с разговора.",
      back: "Вернуться в POC",
      ctaPrompt: "Не нашли ответа на свой вопрос?",
      cta: "Сделать индивидуальный запрос",
      more: "Узнать больше",
      less: "Скрыть FAQ",
      items: [
        { question: "С какими запросами вы работаете?", answer: "Мы координируем личные и профессиональные задачи в сфере бизнеса, недвижимости, релокации, мобильности и цифрового присутствия." },
        { question: "Можно ли отправить индивидуальный запрос?", answer: "Да. Если задача не подходит ни под одно направление, выберите «Индивидуальный запрос» и опишите желаемый результат." },
        { question: "Что произойдёт после отправки?", answer: "Мы изучим запрос, зададим только необходимые вопросы и вернёмся с первым чётким ответом и предложенным следующим шагом." },
        { question: "Какая информация нужна вначале?", answer: "Достаточно коротко описать ситуацию, желаемый результат и сроки. Чувствительные документы на этом этапе отправлять не нужно." },
        { question: "Может ли один запрос включать несколько направлений?", answer: "Да. Сложные задачи можно объединить в один план и вести через одну ответственную точку контакта." },
        { question: "Как обрабатывается моя информация?", answer: "Запрос остаётся в минимально необходимом круге людей. Мы не публикуем кейсы без прямого согласия." },
        { question: "Обязывает ли отправка запроса к сотрудничеству?", answer: "Нет. Запрос запускает разговор; объём работы, стоимость и дальнейшие шаги согласуются отдельно." },
      ],
    },
  },
} as const;

export function copy(locale: Locale) {
  return data[locale];
}

export const pillars: Record<Locale, Record<DirectionKey, LocalizedPillar>> = {
  en: {
    business: {
      title: "Business & Administration",
      tagline: "Your project. Our expertise.",
      summary: "We turn professional and administrative complexity into a clear, coordinated route — from the first brief to local execution.",
      groups: [
        { title: "Before launch", items: ["Business opening", "Market check before launch"] },
        { title: "Administration", items: ["Documents and applications", "Appointments and deadline tracking"] },
        { title: "Local representation", items: ["Specialist and contractor sourcing", "Representation before local organisations"] },
      ],
    },
    property: {
      title: "Property & Management",
      tagline: "Your home. Under control.",
      summary: "From search and acquisition to setup and daily stewardship, one contact keeps your property ready, protected and properly managed.",
      groups: [
        { title: "Search & transaction", items: ["Property search and viewings", "Buying, selling or renting"] },
        { title: "Setup & care", items: ["Pre-purchase property checks", "Move-in and utilities"] },
        { title: "Ongoing management", items: ["Keyholding and home checks", "Maintenance, repairs and emergencies"] },
      ],
    },
    relocation: {
      title: "Relocation & Integration",
      tagline: "A new life. From day one.",
      summary: "We coordinate the practical, administrative and human details of arrival so that a new place begins to feel workable from the first day.",
      groups: [
        { title: "Before arrival", items: ["Move plan and area selection", "Residence documents"] },
        { title: "Arrival & setup", items: ["Temporary housing and arrival", "Banks, insurance and public services"] },
        { title: "Integration", items: ["Schools and healthcare contacts", "Language and family integration"] },
      ],
    },
    mobility: {
      title: "Mobility & Comfort",
      tagline: "Every day. Effortlessly.",
      summary: "Thoughtful travel, transport and everyday coordination keep your time protected and plans moving smoothly.",
      groups: [
        { title: "Getting around", items: ["Chauffeur and private transfers", "Car rental and servicing"] },
        { title: "Travel & stays", items: ["Flights and complex itineraries", "Hotels, villas and restaurants"] },
        { title: "Everyday comfort", items: ["Tickets, reservations and events", "Family and guest logistics"] },
      ],
    },
    brand: {
      title: "Digital & Media Presence",
      tagline: "Your identity. Clear wherever it appears.",
      summary: "We create and coordinate the digital materials that make your presence clear, useful and consistent across the channels your clients and partners use.",
      groups: [
        { title: "Digital identity", items: ["Website and digital business card", "QR contact card"] },
        { title: "Materials", items: ["Presentations and documents", "Business cards and printed materials"] },
        { title: "Content & languages", items: ["Photo, video and content", "Translation and multilingual adaptation"] },
      ],
    },
  },
  fr: {
    business: {
      title: "Entreprise & administration",
      tagline: "Votre projet. Notre expertise.",
      summary: "Nous transformons la complexité professionnelle et administrative en un parcours clair et coordonné — du premier brief à l’exécution locale.",
      groups: [
        { title: "Avant le lancement", items: ["Création d’entreprise", "Vérification du marché avant lancement"] },
        { title: "Administration", items: ["Documents et demandes", "Prise de rendez-vous et suivi des délais"] },
        { title: "Représentation locale", items: ["Recherche de spécialistes et prestataires", "Représentation auprès des organismes locaux"] },
      ],
    },
    property: {
      title: "Immobilier & gestion",
      tagline: "Votre maison. Sous contrôle.",
      summary: "De la recherche et l’acquisition à l’installation puis à la gestion quotidienne, un interlocuteur unique veille sur votre propriété.",
      groups: [
        { title: "Recherche & transaction", items: ["Recherche de bien et visites", "Achat, vente ou location"] },
        { title: "Installation & entretien", items: ["Vérification du bien avant transaction", "Emménagement et mise en service"] },
        { title: "Gestion du bien", items: ["Visites de contrôle et garde des clés", "Entretien, réparations et urgences"] },
      ],
    },
    relocation: {
      title: "Relocation & intégration",
      tagline: "Une nouvelle vie. Dès le premier jour.",
      summary: "Nous coordonnons les aspects pratiques, administratifs et humains de votre arrivée afin que votre nouvelle vie soit opérationnelle dès le premier jour.",
      groups: [
        { title: "Avant l’arrivée", items: ["Plan de déménagement et choix du quartier", "Dossier de résidence"] },
        { title: "Arrivée & installation", items: ["Logement temporaire et arrivée", "Banques, assurances et services publics"] },
        { title: "Intégration", items: ["Écoles et contacts médicaux", "Langue et intégration de la famille"] },
      ],
    },
    mobility: {
      title: "Mobilité & confort",
      tagline: "Chaque jour. Sans effort.",
      summary: "Une coordination attentive de vos déplacements, voyages et demandes quotidiennes protège votre temps et fluidifie chaque projet.",
      groups: [
        { title: "Déplacements", items: ["Chauffeur et transferts privés", "Location et entretien de voiture"] },
        { title: "Voyages & séjours", items: ["Vols et itinéraires complexes", "Hôtels, villas et restaurants"] },
        { title: "Confort quotidien", items: ["Réservations, billets et événements", "Logistique pour la famille et les invités"] },
      ],
    },
    brand: {
      title: "Présence digitale & média",
      tagline: "Votre identité. Claire partout où elle apparaît.",
      summary: "Nous créons et coordonnons les supports digitaux qui rendent votre présence claire, utile et cohérente sur les canaux utilisés par vos clients et partenaires.",
      groups: [
        { title: "Identité digitale", items: ["Site et carte de visite digitale", "Carte de contact QR"] },
        { title: "Supports", items: ["Présentations et documents", "Cartes de visite et supports imprimés"] },
        { title: "Contenu & langues", items: ["Photo, vidéo et contenu", "Traduction et adaptation multilingue"] },
      ],
    },
  },
  ru: {
    business: {
      title: "Бизнес и администрирование",
      tagline: "Ваш проект. Наши знания.",
      summary: "Превращаем профессиональные и административные задачи в понятный, скоординированный процесс — от первого брифа до реализации на месте.",
      groups: [
        { title: "Подготовка к запуску", items: ["Открытие бизнеса", "Проверка рынка перед запуском"] },
        { title: "Администрирование", items: ["Документы и заявления", "Запись на приём и контроль сроков"] },
        { title: "Представительство", items: ["Поиск специалистов и подрядчиков", "Представительство перед местными организациями"] },
      ],
    },
    property: {
      title: "Недвижимость и управление",
      tagline: "Ваш дом. Под контролем.",
      summary: "От поиска и приобретения до обустройства и ежедневного управления — одна точка контакта следит, чтобы недвижимость была готова, защищена и под контролем.",
      groups: [
        { title: "Поиск и сделка", items: ["Поиск объекта и просмотры", "Покупка, продажа или аренда"] },
        { title: "Обустройство и уход", items: ["Проверка объекта перед сделкой", "Переезд и подключение услуг"] },
        { title: "Управление домом", items: ["Проверки дома и хранение ключей", "Ремонт, обслуживание и срочные работы"] },
      ],
    },
    relocation: {
      title: "Релокация и интеграция",
      tagline: "Новая жизнь. С первого дня.",
      summary: "Координируем практические, административные и бытовые детали переезда, чтобы новая жизнь стала понятной и организованной с первого дня.",
      groups: [
        { title: "До приезда", items: ["План переезда и подбор района", "Подготовка документов для ВНЖ"] },
        { title: "Приезд и быт", items: ["Временное жильё и приезд", "Банки, страховка и госслужбы"] },
        { title: "Интеграция", items: ["Школы и медицинские контакты", "Язык и адаптация семьи"] },
      ],
    },
    mobility: {
      title: "Мобильность и комфорт",
      tagline: "Каждый день. Без усилий.",
      summary: "Продуманная координация поездок, транспорта и ежедневных задач сохраняет ваше время и помогает планам двигаться без лишних усилий.",
      groups: [
        { title: "Перемещения", items: ["Водитель и частный трансфер", "Аренда и обслуживание автомобиля"] },
        { title: "Поездки и проживание", items: ["Перелёты и сложные маршруты", "Отели, виллы и рестораны"] },
        { title: "Ежедневный комфорт", items: ["Билеты, бронирования и мероприятия", "Логистика семьи и гостей"] },
      ],
    },
    brand: {
      title: "Цифровое и медиа-присутствие",
      tagline: "Ваша идентичность. Ясно в каждом канале.",
      summary: "Создаём и координируем цифровые материалы, благодаря которым ваше присутствие выглядит ясно, полезно и последовательно для клиентов и партнёров.",
      groups: [
        { title: "Цифровая идентичность", items: ["Сайт и цифровая визитка", "QR-карта контакта"] },
        { title: "Материалы", items: ["Презентации и документы", "Визитки и печатные материалы"] },
        { title: "Контент и языки", items: ["Фото, видео и контент", "Перевод и мультиязычная адаптация"] },
      ],
    },
  },
};

export const directionKeys = Object.keys(pillars.en) as DirectionKey[];
